# Docker Compose Override for Production/Remote Deployments
# This file is automatically loaded by docker-compose and overrides base settings
# Use this for production deployments with Portainer or other orchestrators

services:
  mail-mover:
    # Override environment file loading for production
    # Comment out env_file to rely on environment variables from orchestrator
    env_file: []
    
    # Production-specific resource limits
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1.0'
        reservations:
          memory: 256M
          cpus: '0.2'
    
    # Production logging with rotation
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"
        compress: "true"
    
    # Production health check with longer intervals
    healthcheck:
      test: ["CMD", "/app/health-check.sh"]
      interval: 60s
      timeout: 15s
      retries: 5
      start_period: 60s
    
    # Production restart policy
    restart: always
    
    # Production volumes - use named volumes instead of bind mounts
    volumes:
      - mail-mover-logs:/app/logs
      - mail-mover-data:/app/data

# Named volumes for production
volumes:
  mail-mover-logs:
    driver: local
  mail-mover-data:
    driver: local
