# Local Development Override
# This file is automatically loaded by docker-compose for local development
# It ONLY adds .env file loading - everything else uses base configuration
#
# For production/remote: rename this file to disable it
# Example: mv docker-compose.override.yml docker-compose.override.yml.disabled

services:
  mail-mover:
    env_file:
      - .env
